# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Angular SSR app to Google App Engine - michaelouellette-dev

on:
  push:
    branches:
      - dev

env:
  ARTIFACT_NAME: 'dev-michaelouellette' # set this to the name you want for the artifact
  WEBAPP_PACKAGE_PATH: './dist/'      # set this to the path to your web app project
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.lock') }}
    - name: npm install & build
      run: |
        npm install
        npm run build:production --if-present
    - name: Archive Develop Artifact
      uses: actions/upload-artifact@master
      with:
        name:  ${{ env.ARTIFACT_NAME }}
        path: ${{ env.WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Display structure of downloaded files
        run: |
            # Output artifact contents.
            ls -R
            cat client-secret.json
