name: Prod - Build and deploy

on:
  push:
    branches:
      - production

env:
  ARTIFACT_NAME: 'prod-michaelouellette' # set this to the name you want for the artifact
  WEBAPP_PACKAGE_PATH: './dist'      # set this to the path to your web app project
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.lock') }}
    - name: npm install & build
      run: |
        npm install
        npm run build:production --if-present
        ng build && ng run app:server && npx angular-prerender
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name:  ${{ env.ARTIFACT_NAME }}-${{ github.sha }}
        path: ${{ env.WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@master
        with:
          name: ${{ env.ARTIFACT_NAME }}-${{ github.sha }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./app/browser
